FROM ubuntu:18.04


RUN apt-get update && apt-get install -y curl
# Setup for nvm
RUN mkdir /usr/local/nvm
ENV NVM_DIR /usr/local/nvm 
ENV NODE_VERSION v10.17.0
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash 

RUN /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm use --delete-prefix $NODE_VERSION"

ENV NODE_PATH $NVM_DIR/versions/node/$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/$NODE_VERSION/bin:$PATH


#RUN apt update && apt install -y nodejs npm 

WORKDIR /usr/src/app

COPY . .
RUN chmod 777 /usr/src/app

EXPOSE 8081
EXPOSE 9873

CMD node /usr/src/app/src/main.js